name: dev workflow

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  migration_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:12-3.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: jkr_admin
          POSTGRES_DB: jkr
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Copy the flyway conf
        run: cp db/flyway.conf ./flyway.conf
      - name: Configure the database
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          PGPASSWORD=postgres psql -h postgres -U jkr_admin -d jkr -c "CREATE EXTENSION btree_gist;"
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://postgres:5432/jkr
          user: jkr_admin
          password: postgres
          locations: filesystem:./db/migrations
      - run: echo 'testing completed'
