name: dev workflow

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  migration_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:12-2.5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: jkr
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Copy the flyway conf
        run: cp db/flyway.conf ./flyway.conf
      - uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://localhost:5432/jkr
          user: postgres
          password: postgres
          locations: ./db/migrations
      - run: echo 'testing completed'
