name: dev workflow

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  migration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ireznik/postgis-action@v12
        with:
          postgresql version: "12-2.5" # See https://https://hub.docker.com/r/postgis/postgis for available versions, if it is not specified, use the default value 'latest'
          postgresql password: ${{ secrets.CI_DATABASE_PASSWORD }} # This environment variable sets the superuser password for PostgreSQL, maybe string or secrets, the default superuser is defined by the input environment variable: postgresql user.
          postgresql user: "jkr_admin" # This optional environment variable is used in conjunction with postgresql password to set a user and its password. This variable will create the specified user with superuser power and a database with the same name. If it is not specified, then the default user of 'postgres' will be used.
          postgresql db: "jkr" # This optional environment variable can be used to define a different name for the default database that is created when the image is first started. If it is not specified, then the value of postgresql user will be used.
      - name: Copy the flyway conf
        run: cp db/flyway.conf ./flyway.conf
      - uses: joshuaavalon/flyway-action@v2
        with:
          url: jdbc:postgresql://localhost:5432/jkr
          user: jkr_admin
          password: ${{ secrets.CI_DATABASE_PASSWORD }}
          locations: ./db/migrations
      - run: echo 'testing completed'
